In [1]:
import tensorflow as tf

## Tensorflow 2.0
### Basic with no session

In [3]:
hello = tf.constant("Hello TensorFlow")
tf.print(hello)

Hello TensorFlow


In [4]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)
tf.print(c)

42


### Basic with no placeholder

In [31]:
W = tf.Variable(tf.random.normal([2,3]))
b = tf.Variable(tf.random.normal([2,1]))

In [35]:
x_data = [[1,2,3],[4,5,6]]

In [36]:
@tf.function
def forward(x):
    return W * x + b

In [37]:
print(forward(x_data))

tf.Tensor(
[[-0.44806752 -2.792685    3.7717817 ]
 [-0.43381464 -5.3496127   0.97299886]], shape=(2, 3), dtype=float32)


### MNIST Example

In [45]:
from tensorflow.keras.datasets.fashion_mnist import load_data

In [46]:
(train_images, train_labels), (test_images, test_labels) = load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [ ]:
W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))
y = tf.nn.softmax(tf.matmul())

In [50]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10,activation="softmax")
])

In [52]:
model.compile(optimizer = "adam",
             loss='sparse_categorical_crossentropy',
             metrics=["accuracy"])

In [58]:
model.fit(train_images,train_labels,epochs=20)

Epoch 1/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7545 - accuracy: 0.7107
Epoch 2/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7611 - accuracy: 0.7057
Epoch 3/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7616 - accuracy: 0.7101
Epoch 4/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7412 - accuracy: 0.7115
Epoch 5/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7479 - accuracy: 0.7092
Epoch 6/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7532 - accuracy: 0.7116
Epoch 7/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7545 - accuracy: 0.7101
Epoch 8/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7420 - accuracy: 0.7134
Epoch 9/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.7382 - accuracy: 0.7135
Epoch 10/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.751

In [59]:
model.evaluate(test_images, test_labels, verbose=2)

313/313 - 1s - loss: 0.6799 - accuracy: 0.7304


[0.6799176931381226, 0.730400025844574]

### Graphs

In [77]:
print(tf.Graph().as_default())
g1 = tf.Graph().as_default()
g2 = tf.Graph()
print(g1 is tf.Graph().as_default())
print(g2 is tf.Graph().as_default())

False
False


### Data type

In [78]:
c = tf.constant(4.0, dtype = tf.float64)
print(c)
print(c.dtype)

tf.Tensor(4.0, shape=(), dtype=float64)
<dtype: 'float64'>


### Tensorflow's "flow"

In [79]:
import numpy as np
c = tf.constant([[1,2,3],[4,5,6]])
print("Python List input: {}".format(c.get_shape()))
c = tf.constant(np.array([
    [[1,2,3],
    [4,5,6]],
    [[1,1,1],
    [2,2,2]]
]))
print("3D Numpy array input: {}".format(c.get_shape()))

Python List input: (2, 3)
3D Numpy array input: (2, 2, 3)


In [81]:
c = tf.linspace(0.0,4.0,5)
print("The content of c:\n {}\n".format(c))

The content of c:
 [0. 1. 2. 3. 4.]



### Simple Optimization

In [83]:
init_val = tf.random.normal((1,5),0,1)
var = tf.Variable(init_val, name="var")
print(format(var))

<tf.Variable 'var:0' shape=(1, 5) dtype=float32, numpy=
array([[ 0.66845614,  0.6136779 , -0.8798782 , -0.39099666,  0.08807033]],
      dtype=float32)>


#### Linear Regression

In [141]:
x_data = np.random.randn(2000,3).astype("f")
w_real = [0.3,0.5,0.1]
b_real = -0.2

noise = np.random.randn(3,2000)*0.1
y_data = np.matmul(w_real, x_data.T) + b_real + noise

In [142]:
print(x_data.shape)
print(y_data.T.shape)

(2000, 3)
(2000, 3)


In [131]:
from matplotlib import pyplot as plt

In [132]:
w = tf.Variable([[0,0,0]], dtype = tf.float32,name="weights")
b = tf.Variable(0, dtype=tf.float32,name="bias")

@tf.function
def forward(x):
    return w * x + b

In [145]:
learning_rate = 0.5
optimizer = tf.optimizers.SGD(learning_rate)
for step in range(10+1):
    with tf.GradientTape() as tape:
        y_pred = forward(x_data)
        loss =tf.reduce_mean(tf.square(y_data.T - y_pred))
    
    gradients = tape.gradient(loss, [w,b])
    optimizer.apply_gradients(zip(gradients, [w,b]))
    
    if step % 5 == 0:
        print(step, w.numpy(), b.numpy(), loss)
    

0 [[0.30050057 0.4974353  0.10420057]] -0.20098984 tf.Tensor(0.24388611, shape=(), dtype=float32)
5 [[0.30335966 0.50308394 0.1053647 ]] -0.20095542 tf.Tensor(0.2438464, shape=(), dtype=float32)
10 [[0.30372193 0.50387156 0.10552594]] -0.20094988 tf.Tensor(0.24384566, shape=(), dtype=float32)
